# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/configuration/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - ACTION
  - COPYPASTE
  - DOCKERFILE
  - MARKDOWN_MARKDOWNLINT
  - PyTHON_BANDIT
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_SECRETLINT

DISABLE_ERRORS_LINTERS:
  - JSON
  - MARKDOWN
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - REPOSITORY_TRIVY
  - SPELL
  - YAML

FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.venv|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'

SPELL_FILTER_REGEX_EXCLUDE: (valestyles|\.github|docs/licenses)

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: true
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
