# https://github.com/devcontainers/ci/blob/main/docs/github-action.md

name: 'devcontainer'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
  schedule: # rebuild once a week at midnight on saturday
    - cron: '0 0 * * 6'

env:
  REGISTRY_IMAGE: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        platform:
          - linux/amd64
          # - linux/arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # context: "{{defaultContext}}:${{ github.workspace }}" # tld
          context: ./
          # file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
